# Generated by Django 5.2.1 on 2025-05-25 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('usn', models.CharField(help_text='University Seat Number (matches username)', max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('personal_email', models.EmailField(help_text='Personal email address', max_length=255, unique=True)),
                ('phone_number', models.CharField(help_text='Contact phone number', max_length=15)),
                ('department', models.CharField(choices=[('cse', 'Computer Science & Engineering'), ('ise', 'Information Science & Engineering'), ('aiml', 'AI & Machine Learning'), ('ece', 'Electronics & Communication Engineering'), ('eee', 'Electrical & Electronics Engineering'), ('me', 'Mechanical Engineering'), ('ce', 'Civil Engineering')], max_length=50)),
                ('current_semester', models.CharField(choices=[('1', '1st Semester'), ('2', '2nd Semester'), ('3', '3rd Semester'), ('4', '4th Semester'), ('5', '5th Semester'), ('6', '6th Semester'), ('7', '7th Semester'), ('8', '8th Semester')], max_length=1)),
                ('current_year', models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], max_length=1)),
                ('cgpa', models.FloatField(help_text='Current Cumulative Grade Point Average')),
                ('backlogs', models.IntegerField(default=0, help_text='Number of current backlogs')),
                ('batch', models.CharField(choices=[('2020-2024', '2020-2024'), ('2021-2025', '2021-2025'), ('2022-2026', '2022-2026'), ('2023-2027', '2023-2027'), ('2024-2028', '2024-2028'), ('2025-2029', '2025-2029')], help_text='e.g., 2021-2025', max_length=9)),
                ('domain_priority1', models.CharField(blank=True, choices=[('software', 'Software Development'), ('data_science', 'Data Science'), ('ai_ml', 'AI/Machine Learning'), ('cybersecurity', 'Cybersecurity'), ('hardware_iot', 'Hardware/IoT'), ('cloud_devops', 'Cloud & DevOps'), ('networking', 'Networking'), ('vlsi_embedded', 'VLSI & Embedded Systems'), ('core_mech', 'Core Mechanical'), ('core_civil', 'Core Civil'), ('management_consulting', 'Management/Consulting'), ('finance_fintech', 'Finance/Fintech')], max_length=50, null=True)),
                ('domain_priority2', models.CharField(blank=True, choices=[('software', 'Software Development'), ('data_science', 'Data Science'), ('ai_ml', 'AI/Machine Learning'), ('cybersecurity', 'Cybersecurity'), ('hardware_iot', 'Hardware/IoT'), ('cloud_devops', 'Cloud & DevOps'), ('networking', 'Networking'), ('vlsi_embedded', 'VLSI & Embedded Systems'), ('core_mech', 'Core Mechanical'), ('core_civil', 'Core Civil'), ('management_consulting', 'Management/Consulting'), ('finance_fintech', 'Finance/Fintech')], max_length=50, null=True)),
                ('domain_priority3_choices', models.TextField(blank=True, help_text='Comma-separated values for up to 3 domain choices for priority 3, or use JSONField with PostgreSQL', null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='student_resumes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
            },
        ),
    ]
