# Generated by Django 5.2.1 on 2025-05-26 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='A short label for URLs, e.g., software_development', max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='domain_priority3_choices',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='domain_priority3',
            field=models.ManyToManyField(blank=True, help_text='Select up to 3 domains for Priority 3', related_name='priority3_students', to='home.domain'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='domain_priority1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priority1_students', to='home.domain'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='domain_priority2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priority2_students', to='home.domain'),
        ),
    ]
