# Generated by Django 5.2.1 on 2025-05-26 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_domain_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='slug',
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='domain_priority1',
            field=models.ForeignKey(blank=True, choices=[('cse', 'Computer Science & Engineering'), ('ise', 'Information Science & Engineering'), ('aiml', 'AI & Machine Learning'), ('ece', 'Electronics & Communication Engineering'), ('eee', 'Electrical & Electronics Engineering'), ('me', 'Mechanical Engineering'), ('ce', 'Civil Engineering')], null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priority1_students', to='home.domain'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='domain_priority2',
            field=models.ForeignKey(blank=True, choices=[('cse', 'Computer Science & Engineering'), ('ise', 'Information Science & Engineering'), ('aiml', 'AI & Machine Learning'), ('ece', 'Electronics & Communication Engineering'), ('eee', 'Electrical & Electronics Engineering'), ('me', 'Mechanical Engineering'), ('ce', 'Civil Engineering')], null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='priority2_students', to='home.domain'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='domain_priority3',
            field=models.ManyToManyField(blank=True, choices=[('cse', 'Computer Science & Engineering'), ('ise', 'Information Science & Engineering'), ('aiml', 'AI & Machine Learning'), ('ece', 'Electronics & Communication Engineering'), ('eee', 'Electrical & Electronics Engineering'), ('me', 'Mechanical Engineering'), ('ce', 'Civil Engineering')], help_text='Select up to 3 domains for Priority 3', related_name='priority3_students', to='home.domain'),
        ),
    ]
