# Generated by Django 5.2.1 on 2025-05-26 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_domain_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='current_semester',
            field=models.CharField(choices=[('1', '1st Semester'), ('2', '2nd Semester'), ('3', '3rd Semester'), ('4', '4th Semester'), ('5', '5th Semester'), ('6', '6th Semester'), ('7', '7th Semester'), ('8', '8th Semester')], max_length=10),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='current_year',
            field=models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], max_length=10),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='domain_priority1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='priority1_students', to='home.domain'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='domain_priority2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='priority2_students', to='home.domain'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='domain_priority3',
            field=models.ManyToManyField(help_text='Select up to 3 domains for Priority 3', related_name='priority3_students', to='home.domain'),
        ),
    ]
