# Generated by Django 5.2.1 on 2025-05-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_studentprofile_current_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='domain_priority1',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='domain_priority2',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='domain_priority3',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='domains',
            field=models.ManyToManyField(help_text='Select up to 4 domains of interest.', related_name='student_profiles', to='home.domain'),
        ),
    ]
