# Generated by Django 5.2.1 on 2025-05-27 04:26

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_studentprofile_domain_priority1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='college_email',
            field=models.EmailField(default=1, help_text='Official college email address (ending in @vvce.ac.in)', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.get_student_photo_path),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=home.models.get_student_resume_path),
        ),
    ]
