# Generated by Django 5.2.1 on 2025-05-28 04:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_studentprofile_college_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='certification_links',
            field=models.TextField(blank=True, help_text='Paste links to your certifications or achievements, one link per line.'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='pre_university_percentage',
            field=models.FloatField(blank=True, help_text='Percentage for 12th/PUC or Diploma (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='pre_university_qualification_type',
            field=models.CharField(blank=True, choices=[('12th', '12th / PUC'), ('diploma', 'Diploma')], help_text='Qualification type: 12th/PUC or Diploma', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='tenth_percentage',
            field=models.FloatField(blank=True, help_text='Percentage obtained in 10th standard (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='college_email',
            field=models.EmailField(help_text='Official college email address', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='languages_known',
            field=models.ManyToManyField(blank=True, help_text='Select languages you know.', to='home.language'),
        ),
    ]
