# Generated by Django 5.2.1 on 2025-05-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_language_studentprofile_certification_links_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='certification_links',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='certifications_drive_link',
            field=models.URLField(blank=True, help_text='A single Google Drive/OneDrive/Dropbox link to a folder or PDF containing all your certificates/proof of achievements (optional).', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='certifications_list',
            field=models.TextField(blank=True, help_text="List your certifications or achievements, one per line (e.g., 'Google Cloud Certified - Associate Cloud Engineer', 'Winner of XYZ Hackathon').", null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='github_url',
            field=models.URLField(blank=True, help_text='Link to your GitHub profile', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='hackerrank_url',
            field=models.URLField(blank=True, help_text='Link to your HackerRank profile (optional)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='leetcode_url',
            field=models.URLField(blank=True, help_text='Link to your LeetCode profile (optional)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='Link to your LinkedIn profile', max_length=255, null=True),
        ),
    ]
